import type { NextPage } from 'next'
import React from 'react'
import Header from '@/components/layout/Header'
import Layout from '@/layouts/index'
import styles from '@/styles/pages/Policy.module.scss'

const TermsPage: NextPage = () => {
  return (
    <Layout>
      <div>
        <Header />
        <div className="container">
          <div className={styles['simplePage']}>
            <div className={styles['wysiwyg']}>
              <h1>Terms of Service</h1>
              <p>Last Updated: December 2025</p>

              <h2>1. Acceptance of Terms</h2>
              <p>
                By accessing and using the website and services provided by Layer3Labs ("we," "us," or "our"), you ("User," "you," or "your") agree to comply with and be bound by these Terms of Service ("Terms"). These Terms govern your access to and use of our AI-powered application development platform (the "Service"). If you do not agree to these Terms, please do not access or use our services.
              </p>

              <h2>2. Description of Service</h2>
              <p>
                Layer3Labs provides a comprehensive platform for building, deploying, and managing applications powered by Artificial Intelligence (AI), specifically leveraging OpenAI technologies and other foundation models. You are responsible for obtaining access to the Service, and that access may involve third-party fees.
              </p>

              <h2>3. AI Services and Output</h2>
              <h3>3.1. Artificial Intelligence</h3>
              <p>
                Our Service utilizes artificial intelligence and machine learning technologies. You acknowledge that AI technology is rapidly evolving and that results generated by our Service ("Output") may not always be accurate, complete, or reliable.
              </p>
          <h3>3.2. Ownership of Content</h3>
          <p>
            <strong>Your Input:</strong> You retain all rights, title, and interest in the text, data, and other content you submit to the Service ("Input").
          </p>
          <p>
            <strong>Your Output:</strong> Subject to your compliance with these Terms, Layer3Labs assigns to you all its right, title, and interest in and to the Output generated by the Service based on your Input.
          </p>
          <h3>3.3. Similarity of Output</h3>
          <p>
            Due to the nature of machine learning, Output may not be unique across users and the Service may generate the same or similar output for Layer3Labs or a third party. Other users may input similar questions and receive the same response. Responses that are requested by and generated for other users are not considered your Output.
          </p>

          <h2>4. User Account and Security</h2>
          <p>
            You may be required to register with Layer3Labs to access certain parts of the Service. You agree to provide true, accurate, current, and complete information. You are responsible for maintaining the confidentiality of your password and account and for all activities that occur under your account.
          </p>

          <h2>5. Acceptable Use Policy</h2>
          <p>
            You agree not to use the Service:
          </p>
          <ul>
            <li>To generate content that is illegal, harmful, threatening, abusive, harassment, tortious, defamatory, vulgar, obscene, libelous, or invasive of another's privacy.</li>
            <li>To generate content that promotes discrimination, bigotry, racism, hatred, harassment, or harm against any individual or group.</li>
            <li>To reverse engineer, decompile, or disassemble any aspect of the Service.</li>
            <li>To use the Service to build a competitive product or service.</li>
            <li>To represent that Output from the Service was human-generated when it was not.</li>
          </ul>

          <h2>6. Intellectual Property Rights</h2>
          <p>
            All content included on the Service (excluding your Input and Output), such as text, graphics, logos, images, and software, is the property of Layer3Labs or its suppliers and protected by copyright and other intellectual property laws.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by applicable law, in no event will Layer3Labs be liable for any indirect, incidental, special, punitive, cover, or consequential damages (including, without limitation, damages for lost profits, revenue, sales, goodwill, use of content, impact on business, business interruption, loss of anticipated savings, loss of business opportunity) however caused, under any theory of liability.
          </p>
          <p>
            <strong>AI Disclaimer:</strong> Layer3Labs makes no warranties or guarantees regarding the accuracy, reliability, or completeness of any Output generated by the Service. You are solely responsible for evaluating and verifying the accuracy of any Output before using it.
          </p>

          <h2>8. Indemnification</h2>
          <p>
            You agree to indemnify and hold Layer3Labs harmless from and against any liabilities, losses, damages or costs, including reasonable attorneys' fees, arising from your use of the Service, your Input, your violation of these Terms, or your violation of any third-party rights.
          </p>

          <h2>9. Dispute Resolution</h2>
          <p>
            These Terms shall be governed by the laws of the United States without regard to its conflict of laws provisions. Any disputes shall be resolved exclusively in the state or federal courts located in the United States.
          </p>

          <h2>10. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will provide notice of these changes by updating the "Last Updated" date at the top of these Terms.
          </p>

          <h2>11. Contact Information</h2>
          <p>
            If you have any questions about these Terms, please contact us at:
          </p>
          <ul>
            <li>Email: <a href="mailto:support@layer3labs.io">support@layer3labs.io</a></li>
          </ul>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  )
}

export default TermsPage
